#!/bin/sh

# in config.yaml,
# - set "entrypoint" to "'$BIN/do_bytecode' '$FILENAME' '$TIMEOUT' '$BIN'"
# - set "bin" to "scripts" to add the scripts directory to the mounted volume
# - set "user" to "0" (probably needed, to be able to execute the scripts"

FILENAME="$1"
# full path of file (within docker container) to analyse, e.g. /sb/my_contract.hex

TIMEOUT="$2"
# external timeout in seconds; TIMEOUT=0: no external timeout set

BIN="$3"
# directory with scripts and programs supplied from the outside, typically /sb/bin

# HERE: commands to execute tool, see below for examples

exit

# Mythril
if [ "$TIMEOUT" -eq 0 ]; then
    # no external timeout set
    /usr/local/bin/myth analyze -o json -f "$FILENAME"
else
    # external timeout set to $TIMEOUT seconds
    # TO = TIMEOUT * 80%
    # the remaining 20% are for Mythril to finish
    TO=$(( (TIMEOUT*8+9)/10 ))
    /usr/local/bin/myth analyze --execution-timeout "$TO" -o json -f "$FILENAME"
fi

# Conkas
cd /conkas
python3 conkas.py -fav "$FILENAME"

# Maian
cd /MAIAN/tool
python3 maian.py -c 0 -bs "$FILENAME"
python3 maian.py -c 1 -bs "$FILENAME"
python3 maian.py -c 2 -bs "$FILENAME"


