name: semgrep 
version: c3a9f40 
origin: https://semgrep.dev/ 
info: Find patterns of vulnerabilities in smart contracts based on actual DeFi exploits as well as gas optimization rules that can be used as a part of the CI pipeline.
image: smartbugs/semgrep:c3a9f40
bin: scripts
solidity:
    entrypoint: "'$BIN/do_solidity.sh' '$FILENAME' '$TIMEOUT' '$BIN'"
    solc: yes
    bin: scripts

    
