python smartBugs.py --tool all --dataset access_control --unique-sarif-output
python smartBugs.py --tool all --dataset arithmetic --unique-sarif-output
python smartBugs.py --tool all --dataset bad_randomness --unique-sarif-output
python smartBugs.py --tool all --dataset denial_of_service --unique-sarif-output
python smartBugs.py --tool all --dataset front_running --unique-sarif-output
python smartBugs.py --tool all --dataset reentrancy --unique-sarif-output
python smartBugs.py --tool all --dataset short_addresses --unique-sarif-output
python smartBugs.py --tool all --dataset time_manipulation --unique-sarif-output
python smartBugs.py --tool all --dataset unchecked_ll_calls --unique-sarif-output