#!/bin/sh

FILENAME="$1"

export PATH="/data/bin:$PATH"
chmod +x /data/bin/solc

mkdir /results
java -Xmx16G -jar /securify_jar/securify.jar --livestatusfile /results/live.json --output /results/results.json -fs "$FILENAME"
