#!/bin/sh

FILENAME="$1"
TIMEOUT="$2"
BIN="$3"
SINGLE="$4"

export PATH="$BIN:$PATH"
chmod +x "$BIN/solc"

CONTRACT="${FILENAME%.sol}"
CONTRACT="${CONTRACT##*/}"
CONTRACTS=$(python3 "$BIN"/printContractNames.py "$FILENAME")
OPT_CONTRACT=""
if [ "$SINGLE" -eq 1 ] && (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
    COUNT=1
    OPT_CONTRACT="--target-contracts $CONTRACT"
fi

cd /oyente
/oyente/oyente/oyente.py -s "$FILENAME" $OPT_CONTRACT
