#!/bin/sh

FILENAME="$1"
TIMEOUT="$2"
BIN="$3"
MAIN="$4"

export PATH="$BIN:$PATH"
chmod +x "$BIN/solc"

CONTRACT="${FILENAME%.sol}"
CONTRACT="${CONTRACT##*/}"
CONTRACTS=$(python3 "$BIN"/printContractNames.py "$FILENAME")

OPT_CONTRACT=""
if [ "$MAIN" -eq 1 ]; then
    if (echo "$CONTRACTS" | grep -q "$CONTRACT"); then
        OPT_CONTRACT="--target-contracts $CONTRACT"
    else
        echo "Contract '$CONTRACT' not found in $FILENAME"
        exit 16
    fi
fi

cd /oyente
/oyente/oyente/oyente.py -s "$FILENAME" $OPT_CONTRACT
