name: Solhint
version: "6.0.0"
origin: https://github.com/protofire/solhint
info: Open source project for linting solidity code. This project provide both security and style guide validations.
image: smartbugs/solhint:6.0.0
solidity:
    entrypoint: "'$BIN/do_solidity.sh' '$FILENAME' '$BIN'"
    solc: yes
    bin: scripts
