#!/bin/sh

FILENAME="$1"
TIMEOUT="$2"
BIN="$3"
SB=$(dirname "$FILENAME")

cd /home/reviewer/gigahorse-toolchain/logic
./analyze.py --reuse_datalog_bin --restart --rerun_clients -d "$SB" -C ../../ethainter-inlined.dl
