#!/bin/sh

FILENAME="$1"
TIMEOUT="$2"
SB=$(dirname "$FILENAME")

OPT_TIMEOUT=""
if [ "$TIMEOUT" -gt 0 ]; then
    # TO = TIMEOUT * 80%
    # the remaining 20% are for ethainter to finish
    TO=$(( (TIMEOUT*8+9)/10 ))
    OPT_TIMEOUT="-T $TO"
fi

cd /home/reviewer/gigahorse-toolchain/logic
./analyze.py --reuse_datalog_bin --restart --rerun_clients $OPT_TIMEOUT -d "$SB" -C ../../ethainter-inlined.dl
