#!/bin/sh

FILENAME="$1"
BIN="$2"

export PATH="$BIN:$PATH"
chmod +x $BIN/solc

for CONTRACT in `python3 $BIN/printContractNames.py "$FILENAME"`; do
    cd /MAIAN/tool; 
    for c in 0 1 2; do
        python3 maian.py -c "$c" -s "$FILENAME" "$CONTRACT"
    done
done
