#!/bin/sh

FILENAME="$1"
TIMEOUT="$2"
BIN="$3"

export PATH="$BIN:$PATH"
chmod +x "$BIN/solc"

touch /root/results.json

if [ "$TIMEOUT" -lt 20 ]; then
  python3 fuzzer/main.py -s "$FILENAME" --evm byzantium --results results.json --seed 1427655
else
  TO=$((TIMEOUT - 10))
  python3 fuzzer/main.py -s "$FILENAME" --evm byzantium --results results.json --seed 1427655 --timeout $TO
fi
