#!/bin/sh

FILENAME="$1"
TIMEOUT="$2"
BIN="$3"

export PATH="$BIN:$PATH"
chmod +x "$BIN/solc"

touch /root/results.json

count=0
for _ in $(python3 "$BIN"/printContractNames.py "$FILENAME"); do
  count=$((count + 1))
done

# Fuzz each contract at least 10 seconds
to=$(((TIMEOUT - (10 * count)) / count))
if [ "$TIMEOUT" -eq 0 ] || [ $to -lt 10 ]; then
  python3 fuzzer/main.py -s "$FILENAME" --evm byzantium --results results.json --seed 1427655
else
  python3 fuzzer/main.py -s "$FILENAME" --evm byzantium --results results.json --seed 1427655 --timeout $to
fi
