name: Mando
version: 0.1
origin: https://github.com/stephan-klein/ge-sc-machine
info: The MANDO project is an open-source research initiative that endeavors to acquire an understanding of the structures of diverse smart contract graphs. The project's primary objective is to detect vulnerabilities in the source code and bytecode of smart contracts, both at the coarse-grained contract-level and fine-grained line-level, with a high degree of accuracy. The core engines of the MANDO project are constructed on the foundation of state-of-the-art heterogeneous deep graph learning methodologies.
image: deet0x/mando:0.1 # id of Docker image (mandatory)
output: /app/output.json
bin: scripts # folder with programs that will be accessible in the Docker container
# add the section below if the tool is able to analyse Solidity source code
solidity:
    entrypoint: "'$BIN/do_solidity.sh' '$FILENAME' '$TIMEOUT' '$BIN' '$MAIN'"
    solc: yes

# bytecode:
#     entrypoint: "'$BIN/do_bytecode.sh' '$FILENAME' '$TIMEOUT'"
# runtime:
#     entrypoint: "'$BIN/do_runtime.sh' '$FILENAME' '$TIMEOUT'"
